### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by cpieringer** [menpo/conda-opencv3#2]
Hi,

can I use these recipes on windows? 

```
conda install /PATH/TO/OPENCV3/PACKAGE.tar.gz
```

What is the path if I use source from git of opencv, I have not that file.

Best regards

**Comment by patricksnape** [comment]
Yes you can use this on Windows - if you successfully ran the commands I listed, you will get a `.tar.gz` file (conda prints the path to it when it tells you that you can upload it to binstar) containing the OpenCV3 Python conda package which can be installed as you gave.

You **cannot** use the git repository because this set of recipes is full of patches that make the code actually compile - these **rely** on the specific 3.0.0 release of OpenCV3 and OpenCV-contrib.

**Comment by cpieringer** [comment]
I noted that conda requires a package called patch and give me an error message:

<i>Applying patch: C:/ ... _mjpeg_decoder.patch
Did not find 'patch' in C:\Anaconda3....
</i>

I tried to install it directly using anaconda 3 but this package depends on python 2.7. Then I installed a version for python 3.4 using pip. But conda cannot use it.

Do you have experience with this issue?

Thank you in advance,
CHristian

**Comment by patricksnape** [comment]
If you have correctly placed the `conda` binary directory on your path then `conda` ships with the `patch` utility. Regardless, you could use something like [cmder](http://gooseberrycreative.com/cmder/) as your shell, which will also give you `patch`. Run `conda build` from inside a cmder shell and enjoy the Unix-like experience :)

> > I tried to install it directly using anaconda 3 but this package depends on python 2.7. Then I installed a version for python 3.4 using pip. But conda cannot use it.

I don't know what you meant by this? What package depends on Python 2.7? This repo makes builds for all Python versions. Try:

```
set CONDA_PY=34
conda build conda
```

To build the Python 3.4 version inside a Python 2.7 Miniconda environment.

**Comment by cpieringer** [comment]
@patricksnape I tried your advice, however patch does not exist in my conda installation. The cmder shell works but it also gives me an error about missing patch.

**Comment by patricksnape** [comment]
Hmm. I'm confused why this works for me and not you! It definitely ships with conda otherwise the conda meta.yaml couldn't contain the patch section. Try grabbing the patch command from [here](http://gnuwin32.sourceforge.net/packages/patch.htm) and putting it on your path (maybe in the conda `bin` folder?) If it still fails as missing patch then you aren't placing it on your path correctly!

**Comment by patricksnape** [comment]
Also - as a note: this is exactly why I provide this repository - because building this software is a nightmare. I cannot stress more that you shouldn't bother trying to build it unless _you absolutely have to_. Why don't you just use conda?

**Comment by cpieringer** [comment]
@patricksnape I will try download and put patch in the bin folder. I want to build the library beacuse I am using Python 3. Conda only install opencv for python 2.7. But if there are not other solution, I will use Python 2.7 with the conda installation. Thank you very much!

Best regards.

**Comment by patricksnape** [comment]
You don't need to, conda will install OpenCV3 for Python 3, just install it from my repository! Seriously, run these commands:

```
conda create -n opencv3 python=3
activate opencv3
conda install -c menpo opencv3
```

That should install OpenCV3 in a Python 3 environment!
