### ISSUE TITLE
build error in macOS Sierra

### ISSUE THREAD

**Issue by hsiaray** [menpo/conda-opencv3#31]
fatal error: 'QTKit/QTKit.h' file not found

It seems Quicktime is not supported in new macOS.

**Comment by MathGrelck** [comment]
Also having this issue. Seems like QTKit is deprecated. Discussion at the [official opencv repo](https://github.com/Homebrew/homebrew-science/issues/4303).
Since this issue has been resolved in the source code a long time ago, the solution is to build a newer version of opencv.
On a related note, I'm also having issues with versions <=3.2.0 not releasing the iSight camera on my macbook pro correctly. The issue was [resolved](https://github.com/opencv/opencv/pull/8274) on 26 of february 2017 and is included in the latest opencv 3.3.0.
Is it possible to update this repo to build for v3.3.0?

**Comment by patricksnape** [comment]
Please use the conda-forge package
